---
title: "Analysis Code"
author: "Yuxin Zeng"
date: "2020/9/26"
output: pdf_document
---

```{r setup, include=FALSE}
pacman::p_load("knitr","ggplot2","rstanarm","tidyverse","lubridate","dplyr","tseries","TTR","TSA","forecast","astsa")
```

```{r include=FALSE}
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

install.packages("devtools")
library(devtools)
install_github("kassambara/easyGgplot2")
library(easyGgplot2)
```

## 3.Data Preprocessing
```{r}
load("C:/Users/lenovo/Desktop/615 R/buoy/MR.RData")
buoy = data.frame(MR)
buoy_1 = buoy %>% filter(YYYY >= "1997") 
buoy_2 = buoy_1 %>% filter(hh == "12")
buoy_3 = buoy_2[,c(1,2,3,13)]
buoy_4 = buoy_3[buoy_3$ATMP<99.0,]
buoy_5 = buoy_4 %>% unite(date,YYYY,MM,DD,sep="-")

write.csv(buoy_4,file="C:/Users/lenovo/Desktop/615 R/buoy/Everyday.csv")
write.csv(buoy_5,file="C:/Users/lenovo/Desktop/615 R/buoy/Everyday_date.csv")
```

## 4.Data Analysis & Visualization
Calculate the average temperature for each month from 1997 to 2016.
```{r echo=FALSE}
buoy=read.csv("Everyday.csv",header=TRUE)
Jan=0
for(i in 1997:2016){Jan[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="01"])}
Feb=0
for(i in 1997:2016){Feb[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="2"])}
Mar=0
for(i in 1997:2016){Mar[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="3"])}
Apr=0
for(i in 1997:2016){Apr[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="4"])}
May=0
for(i in 1997:2016){May[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="5"])}
Jun=0
for(i in 1997:2016){Jun[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="6"])}
Jul=0
for(i in 1997:2016){Jul[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="7"])}
Aug=0
for(i in 1997:2016){Aug[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="8"])}
Sep=0
for(i in 1997:2016){Sep[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="9"])}
Oct=0
for(i in 1997:2016){Oct[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="10"])}
Nov=0
for(i in 1997:2016){Nov[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="11"])}
Dec=0
for(i in 1997:2016){Dec[i-1996]=mean(buoy$ATMP[buoy$YYYY==i|buoy$MM=="12"])}

atmp=cbind.data.frame(Year=1997:2016,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec)
write.csv(atmp,file="C:/Users/lenovo/Desktop/615 R/buoy/atmp.csv")
```

```{r echo=FALSE}
atmp=read.csv("atmp.csv",header=TRUE)
atmp=data.frame(atmp)

p1=ggplot(atmp,aes(x=X,y=Jan))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Jan),col="blue")+labs(x="Year",y="Air Temp",title = "Jan")
p2=ggplot(atmp,aes(x=X,y=Feb))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Feb),col="blue")+labs(x="Year",y="Air Temp",title = "Feb")
p3=ggplot(atmp,aes(x=X,y=Mar))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Mar),col="blue")+labs(x="Year",y="Air Temp",title = "Mar")
p4=ggplot(atmp,aes(x=X,y=Apr))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Apr),col="blue")+labs(x="Year",y="Air Temp",title = "Apr")
p5=ggplot(atmp,aes(x=X,y=May))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(May),col="blue")+labs(x="Year",y="Air Temp",title = "May")
p6=ggplot(atmp,aes(x=X,y=Jun))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Jun),col="blue")+labs(x="Year",y="Air Temp",title = "Jun")
p7=ggplot(atmp,aes(x=X,y=Jul))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Jul),col="blue")+labs(x="Year",y="Air Temp",title = "Jul")
p8=ggplot(atmp,aes(x=X,y=Aug))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Aug),col="blue")+labs(x="Year",y="Air Temp",title = "Aug")
p9=ggplot(atmp,aes(x=X,y=Sep))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Sep),col="blue")+labs(x="Year",y="Air Temp",title = "Sep")
p10=ggplot(atmp,aes(x=X,y=Oct))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Oct),col="blue")+labs(x="Year",y="Air Temp",title = "Oct")
p11=ggplot(atmp,aes(x=X,y=Nov))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Nov),col="blue")+labs(x="Year",y="Air Temp",title = "Nov")
p12=ggplot(atmp,aes(x=X,y=Dec))+geom_point()+geom_smooth(method=lm,col="green")+geom_abline(slope=0,intercept=mean(Dec),col="blue")+labs(x="Year",y="Air Temp",title = "Dec")

ggplot2.multiplot(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,cols=4)
```


## 5.Seasonal ARIMA
#Data preparation: 
```{r}
atmp=read.csv(file="atmp.csv",header=TRUE)
atmpt=t(atmp)
atmpt1=atmpt[-c(1,2),]
atmpv=as.vector(atmpt1)
atmpts=ts(atmpv,frequency=12)
tsdisplay(atmpts,xlab="Year",ylab="Air Temp")

write.csv(atmpv,file="C:/Users/lenovo/Desktop/615 R/buoy/atmpv.csv")
```
 

#Seasonal ARIMA
```{r}
#Fit the Time Series
fit1=auto.arima(atmpts)
print(fit1)

#Check the Residuals
tsdisplay(residuals(fit1))
checkresiduals(fit1)

#Predict Air Temperature of the Next Three Years
fore1=forecast(fit1,h=3*12)
plot(fore1)
lines(fore1$fitted,col="blue")
lines(atmp,col="yellow")

#Eliminate Seasonal Effects
atmpts_components=decompose(atmpts)
plot(atmpts_components)
atmpts_seasonallyadjusted=atmpts-atmpts_components$seasonal
plot(atmpts_seasonallyadjusted)

fit2=auto.arima(atmpts_seasonallyadjusted)
print(fit2)
fore2=forecast(fit2,h=3*12)
par(mfrow=c(2,1))
plot(fore1)
lines(fore1$fitted,col="blue")
lines(atmp,col="yellow")
plot(fore2)
lines(fore2$fitted,col="blue")
lines(atmp,col="yellow")
```

