---
title: "Import"
author: "Yuxin Zeng"
date: "2020/9/25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("knitr","ggplot2","rstanarm","tidyverse","lubridate")
```


```{r}
### make URLs

url1 <- "http://www.ndbc.noaa.gov/view_text_file.php?filename=mlrf1h"
url2 <- ".txt.gz&dir=data/historical/stdmet/"

years <- c(1987:2016)

urls <- str_c(url1, years, url2, sep = "")

filenames <- str_c("ma", years, sep = "")

###  Read the data from the website

N <- length(urls)

for (i in 1:N){
  suppressMessages( ###  This stops the annoying messages on your screen.  Do this last.
    assign(filenames[i], read_table(urls[i], col_names = TRUE))
  )
  
  file <- get(filenames[i])
  
  x <- ncol(file)

  
#Since data from different year has different columns, we seperate them and only take the columns we want  
  if(x %in% c(15,16)){
      colnames(file)[1] <-"YYYY"
      colnames(file)[2] <-"MM"
      colnames(file)[3] <-"DD"
      colnames(file)[4] <-"hh"
      colnames(file)[12] <-"Air_tmp"
      colnames(file)[13] <-"Water_tmp"
      file <- file[,c(1,2,3,4,12,13)]
  }
  if(x==17){
      colnames(file)[1] <-"YYYY"
      colnames(file)[2] <-"MM"
      colnames(file)[3] <-"DD"
      colnames(file)[4] <-"hh"
      colnames(file)[13] <-"Air_tmp"
      colnames(file)[14] <-"Water_tmp"
      file <- file[,c(1,2,3,4,13,14)]
  }

#Combine all dataframes
  if(i == 1){
    MR <- file
  }

  else{
    MR <- rbind.data.frame(MR, file)
  }
}
```

